### ISSUE TITLE
Facebook "An active token must be used" error [0.7.1]

### ISSUE THREAD

**Issue by trafnar** [oauth-xx/oauth2#103]
I was successfully using 0.0.3 to access facebook and I'm trying to upgrade to 0.7.1. I've followed the example quite closely and read through the issues but always run into the error:

`An active access token must be used to query information about the current user.`

I'm not sure if that means I'm somehow not using an access token, or that my access token is not "active".

Here is the code I am using:

```
# create client
client = OAuth2::Client.new(APP_ID, APP_SECRET, :site => BASE_URL, :token_url => '/oauth/access_token')

# get auth url
client.auth_code.authorize_url(:redirect_uri => CALLBACK_URI)

# create token
token = client.auth_code.get_token(params[:code], :redirect_uri => CALLBACK_URI)

# attempt get
token.get('/me') # => "An active access token must be used to query information about the current user."

```

Is there an obvious mistake I am making here?

**Comment by galois17** [comment]
Closing this issue. You can you can call get_token with an optional hash now.

https://github.com/oauth-xx/oauth2/blob/e7bbdfa86f3821797e5c25623e33e0d29cf72ed5/lib/oauth2/strategy/auth_code.rb#L27
