### ISSUE TITLE
Infinite loop (memory leak)

### ISSUE THREAD

**Issue by danger89** [oauth-xx/oauth2#124]
Sometimes we get a 401 (unautorized from OAuth2::Error), most of the time the access token is expired which we use on the client side to connect to our API / server side (RestFull interface of our models in Ruby on Rails). It also happens with error codes like 602, etc. Only errors within the 200 range gives no problems.

The big issue is we try to begin/rescue the error in some way, but it has no effect. The application (client) will try over and over again to request the URL which keep returning 401 (or 602 or any other HTTP error except the 200 OK). This loop will eat all the memory and swap of the system. If we delete the Error.new() part the infinite loop is gone..

My code:

```
def current_user    
 begin
  if access_token
     response = access_token.get("/api/users/current")
     if response.status == 200
       @current_user ||= response.parsed
     else
       @current_user = nil
     end
   else
     @current_user = nil
   end
 rescue    
   error_handling("Current user get failed", 3,"index")

   redirect_to Rails.application.config.url[:acs_api] + "/logout", alert: "Access token expired, try signing in again."
 end            
end
helper_method :current_user
```

Oauth2 code:

```
def request(verb, url, opts={})
  url = self.connection.build_url(url, opts[:params]).to_s

  response = connection.run_request(verb, url, opts[:body], opts[:head$
    yield(req) if block_given?
  end
  response = Response.new(response, :parse => opts[:parse])

  case response.status
  when 301, 302, 303, 307
    opts[:redirect_count] ||= 0
    opts[:redirect_count] += 1
    return response if opts[:redirect_count] > options[:max_redirects]
    if response.status == 303
      verb = :get
      opts.delete(:body)
    end
    request(verb, response.headers['location'], opts)
  when 200..299, 300..399
    # on non-redirecting 3xx statuses, just return the response
    response
  when 400..599
    #e = Error.new(response) # if i comment this 3 lines, the loop is gone
    #raise e if opts[:raise_errors] || options[:raise_errors]
    #response.error = e
    response
  else
    #raise Error.new(response), "Unhandled status code value of #{response.status}"  # same..
    response
  end
end
```

The development.log of the client (we took HTTP 600 error as example):
http://pastebin.com/hdPAr1jH

Instead of modify your code, you know some solution to our problem?

Thanks in advance!

Kind regards,
Melroy van den Berg

**Comment by pboling** [comment]
The oauth2 error is raised inside your app code begin/end, which rescues it and redirects to a route that will likely call `current_user`, thus continuing the cycle forever.  In any case, this is not a bug in oauth2.  Designing error handling can be complex.

**Comment by danger89** [comment]
Thanks for your answer, even after 6 (six) years.. :+1:

**Comment by pboling** [comment]
Just took over the project, trying to clean out the gutters. 🥇
