### ISSUE TITLE
OAuth Request without AccessToken?

### ISSUE THREAD

**Issue by Mike-Petersen** [oauth-xx/oauth2#127]
Everything is working fine with authentication and making requests with an access token.

But what i can not find out is how to make a request without an access token. I thought it would simply work with

client = OAuth2::Client.new(key, secret, :site => site)
client.request(:post, "/api/users", {params: {param1: "val1"}})
but that does not seem to work. It is not setting any oauth header in the request.

How do i make a request like that?

In my case i only have a token if it is a request from a user, but some request are just done by the application not regarding any userm so i do not have a user token (AccessToken).

**Comment by josephpage** [comment]
You can do non-authenticated request by calling the Faraday client directly : 
`client.connection.request(:post, "/api/users", {params: {param1: "val1"}})`
