### ISSUE TITLE
Unable to use with Yahoo API

### ISSUE THREAD

**Issue by wafendy** [oauth-xx/oauth2#132]
I can't get this to work with Yahoo OAuth server.  I wonder who is not following the standard. Has anyone successfully used this gem and authenticated with Yahoo OAuth server?

**Comment by josephpage** [comment]
Hey wafendy,
Sorry for the delay.
Have you found a solution to connect Yahoo APIs? Can you share the solution?

**Comment by pboling** [comment]
Closing.  https://stackoverflow.com/a/25798238/213191
