### ISSUE TITLE
[Linkedin] POST from access_token to send message

### ISSUE THREAD

**Issue by hb-shanmuk** [oauth-xx/oauth2#141]
I am using oauth2 for linked in authentication and getting profile,send message and invite a member by id.I have observed that get methods are working properly for linkedIn but there is a problem with post method to send body(XML) as a parameter.I have tried the following but throwing so many errors.

```
                message_body = "<?xml version='1.0' encoding='UTF-8'?>
                        <mailbox-item>
                            <recipients>
                                <recipient>
                                    <person path='/people/~' />
                                </recipient>
                                <recipient>
                                    <person path='/people/sEu0dKDNv3' />
                                </recipient>
                            </recipients>
                <subject>  phase2</subject>
               <body>You're certainly the best person for the job @ heyyy</body>
                        </mailbox-item>"
```

response = access_token.post('https://api.linkedin.com/v1/people/~/mailbox',:body=>message_body)

Thanks for help

**Comment by pboling** [comment]
It is unlikely that this question is still relevant to the current version of anything, so will be closing this soon if no further responses.

**Comment by pboling** [comment]
This gem should provide a good example of how to do it, or you could just use the gem:
https://github.com/emorikawa/linkedin-oauth2
