### ISSUE TITLE
Support for text/json content type

### ISSUE THREAD

**Issue by krsyoung** [oauth-xx/oauth2#148]
Hi, it would be great if CONTENT_TYPES defined in response.rb would also support text/json in addition to application/json so that the :json parsing strategy would be applied to the body.

For example:

```
CONTENT_TYPES = {
  'application/json' => :json,
  'text/json' => :json,
  'text/javascript' => :json,
  'application/x-www-form-urlencoded' => :query,
  'text/plain' => :text
}
```

Thanks!

**Comment by johaywood** [comment]
This seems to have already been taken care of with [`OAuth2::Response.register_parser`](https://github.com/oauth-xx/oauth2/blob/master/lib/oauth2/response.rb#L32)

I'm using something in an initializer like this to handle an API that provides json with a capital 'J'
```ruby
OAuth2::Response.register_parser(:json, [Mime::JSON.to_s, 'application/Json'] => :json) do |body|
  MultiJson.load(body).with_indifferent_access rescue body
end
```
or unusual keys in the access token response that don't play well with the defaults in the gem
```ruby
OAuth2::Response.register_parser(:access_token_json, [Mime::JSON.to_s, 'application/Json'] => :json) do |body|
  MultiJson.load(body).transform_keys! { |k| k.to_s.underscore }.with_indifferent_access rescue body
end
```
then to use that parser for specific requests that require it 
```ruby
access_token.refresh!(parse: :access_token_json)
```

**Comment by pboling** [comment]
@krsyoung This appears [to be fixed as shown ](https://github.com/oauth-xx/oauth2/issues/148#issuecomment-364209777) by @johaywood.  Closing.

**Comment by krsyoung** [comment]
I have unfortunately long since moved away from the related project to validate.  Sorry I didn't get back to @thejonanshow with code when I still had the context.  Thanks @johaywood for the current workaround!
