### ISSUE TITLE
Unable to activate jwt-0.1.8, because multi_json-1.3.7 conflicts with multi_json (>= 1.5) (Gem::LoadError)

### ISSUE THREAD

**Issue by sulomenon** [oauth-xx/oauth2#153]
Unable to activate jwt-0.1.8, because multi_json-1.3.7 conflicts with multi_json (>= 1.5) (Gem::LoadError)
    from /home/sato/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1163:in `activate'
    from /home/sato/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1199:in`block in activate_dependencies'
    from /home/sato/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1185:in `each'
    from /home/sato/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1185:in`activate_dependencies'
    from /home/sato/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1167:in `activate'
    from /home/sato/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems.rb:181:in`rescue in try_activate'
    from /home/sato/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems.rb:178:in `try_activate'
    from /home/sato/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:109:in`rescue in require'
    from /home/sato/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in `require'

**Comment by xtagon** [comment]
@sulomenon Are you still seeing this issue on the latest version?

**Comment by pboling** [comment]
This should be resolved in master.  Reopen if it gets reported again.
