### ISSUE TITLE
[Linkedin] post not work for me

### ISSUE THREAD

**Issue by gaohongwei** [oauth-xx/oauth2#161]
This is my code

 def client
   OAuth2::Client.new(
      API_KEY,
      API_SECRET,
      :authorize_url => "/uas/oauth2/authorization?response_type=code", #LinkedIn's authorization path
      :token_url => "/uas/oauth2/accessToken", #LinkedIn's access token path
      :site => "https://www.linkedin.com"
    )
 end

access_token = OAuth2::AccessToken.new(client, token, {
              :mode => :query,
              :param_name => "oauth2_access_token",
              })

get works well
response = access_token.get('https://api.linkedin.com/v1/people/~?format=json')

header= { 'Content-Type' => 'json'}
body={ 
"comment"=>"This is my cloud",
"content"=>{"title"=>"OTI cloud",
            "submitted-url"=>"http://www.apple.com",
             "submitted-image-url"=>"http://www.apple.comlogo.jpg",
             "description"=> "my cloud"},
"visibility"=> {"code"=> "anyone"}
}
data={ :body=>body,:header=>header}

res = access_token.post("https://api.linkedin.com/v1/people/~/shares", data)
###### 

I got this error
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<error>
<status>400</status>
<timestamp>1388966419969</timestamp>
<request-id>RB9Q9LNGKC</request-id>
<error-code>0</error-code>
<message>Couldn't parse share document: error: Unexpected end of file after null</message>

**Comment by xtagon** [comment]
@gaohongwei Is this still an issue you can reproduce on the latest versions?

**Comment by pboling** [comment]
This is exactly the same issue as https://github.com/oauth-xx/oauth2/issues/141

Marking stale, and will close both soon if there is no further input.

**Comment by pboling** [comment]
This gem should provide a good example of how to do it, or you could just use the gem:
https://github.com/emorikawa/linkedin-oauth2
