### ISSUE TITLE
Hiding exceptions is dangerous

### ISSUE THREAD

**Issue by elia** [oauth-xx/oauth2#167]
The plain rescue in MultiJson can potentially hide useful exceptions (intridea/multi_json#143)

``` ruby
:json  => lambda { |body| MultiJson.load(body) rescue body }, # rubocop:disable RescueModifier`
```

https://github.com/intridea/oauth2/blob/3d0ad2df0a3dd7e31b103e621dc3cfcd9895ca42/lib/oauth2/response.rb#L53

That's probably why rubocop complaints in the first place :frog:. 

Assuming the `rescue` is there for bad content-types and not to hide MultiJson errors, wouldn't it be better to ask the user to fix the issue himself by setting the parser?

**Comment by pboling** [comment]
I agree.  The next release will include breaking changes, and we will stop rescuing during parsing.

**Comment by pboling** [comment]
Fixed by https://github.com/oauth-xx/oauth2/pull/367

**Comment by pboling** [comment]
This will require significant investigation, testing, and perhaps redesign.
