### ISSUE TITLE
unnecessary params in url

### ISSUE THREAD

**Issue by t0pep0** [oauth-xx/oauth2#168]
I create a client:
vk_client = OAuth2::Client.new(vk_id, vk_secret,  :site => 'https://vk.com',
:authorize_path => 'https://oauth.vk.com/authorize',
 :access_token_path => 'https://oauth.vk.com/access_token')
And try to get access_token:
vk_client.web_server.access_token(code, :redirect_uri => vk_redirect)
And i have error, due to unnecessary parameter in the query
?act=s&client_id=%my_client_id%&client_secret=%my_client_secret%&code=%my_code%&grant_type=authorization_code&pid=28264373&redirect_uri=%my_redirect_uri%&subdir=oauth&subsubdir=token
Parametr "act" is unnecessary and i don't know  where does it come

**Comment by samarthsikotara** [comment]
How did you get the code value?

**Comment by sandipramani** [comment]
exports.getHome = function(req, res) {
    code = req.query.code;
}

**Comment by pboling** [comment]
@jhmoore you've had your fingers in the relevant places recently.  Any idea where a random parameter like `act` might come from?

It certainly could be any other middleware injecting it, and wholly unrelated to OAuth2.

**Comment by pboling** [comment]
Actually the term `act` never appears in this codebase, so it is unlikely to be a bug in this codebase.  Closing.
