### ISSUE TITLE
Storing one response rather than logging all of them?

### ISSUE THREAD

**Issue by fj** [oauth-xx/oauth2#184]
I'd like to store the HTTP response after a client makes a request.

I know I can set OAUTH_DEBUG, but that logs it rather than stores it, and I want to store one specific response rather than logging it for every invocation. Is there a way to do that?

**Comment by xtagon** [comment]
Possibly related to https://github.com/oauth-xx/oauth2/issues/186

**Comment by pboling** [comment]
Resolved by #298
