### ISSUE TITLE
get_token should put Response headers and status in the AccessToken object

### ISSUE THREAD

**Issue by veetow** [oauth-xx/oauth2#186]
It would be very useful for debugging to have the `Response.header` and `Response.status` parameters merged into the returned `AccessToken` object as there's no way to bubble that full `Response` object up when calling the `get_token` method.

**Comment by jskirst** [comment]
In addition to debugging, I've run into a situation where the response contains a header value that is necessary for further requests.

**Comment by xtagon** [comment]
Anyone up for doing a PR?

**Comment by pboling** [comment]
Resolved by #298
