### ISSUE TITLE
Client secret found in GET URI MUST not exist

### ISSUE THREAD

**Issue by maletor** [oauth-xx/oauth2#193]
“The parameters can only be transmitted in the request-body and MUST NOT be included in the request URI.”

From the OAuth spec, we should not allow client_secret to ever appear in the URL, yet there is [a spec for it](https://github.com/intridea/oauth2/blob/master/spec/oauth2/strategy/auth_code_spec.rb#L12).

**Comment by pboling** [comment]
Fix will be release in v2.0.0
