### ISSUE TITLE
GitHub OAuth2

### ISSUE THREAD

**Issue by radar** [oauth-xx/oauth2#199]
I've tried to use the oauth2 gem to do the authorization flow with GitHub. The authorization endpoint itself is fine, but when I try to do a token request I get this:

```
OAuth2::Error - Cookies must be enabled to use GitHub.:
    /Users/ryan/.gem/ruby/2.1.2/gems/oauth2-1.0.0/lib/oauth2/client.rb:113:in `request'
    /Users/ryan/.gem/ruby/2.1.2/gems/oauth2-1.0.0/lib/oauth2/client.rb:138:in `get_token'
    /Users/ryan/.gem/ruby/2.1.2/gems/oauth2-1.0.0/lib/oauth2/strategy/auth_code.rb:29:in `get_token'
       ...
```

The app I'm using is my [oauth2_test](https://github.com/radar/oauth2-test/tree/github_auth_code) Sinatra app.

Is there an option on the oauth2 gem side of things to enable cookies?

**Comment by lmmendes** [comment]
Have you tried to use the `cookie_jar` gem (https://github.com/miyagawa/faraday-cookie_jar)

And trying to initialize the oauth2 gem using

```
options = {
  connection_build: lambda { |builder| builder.use :cookie_jar  }
}
oauth = OAuth2::Client.new(client_id, client_secret, options)
```

Sorry but didn't try the code just read the connection portion of the source code https://github.com/intridea/oauth2/blob/master/lib/oauth2/client.rb#L55

**Comment by xtagon** [comment]
@radar Did the suggestion from Immendes solve the issue?

**Comment by radar** [comment]
@xtagon asking me to remember something from two years ago is a bit of a stretch.

I don’t remember

**Comment by xtagon** [comment]
@radar Appologies. Just didn't want to close without asking :)

**Comment by radar** [comment]
Thank you for asking anyway :)
