### ISSUE TITLE
no _dump_data is defined for class Proc

### ISSUE THREAD

**Issue by filkaris** [oauth-xx/oauth2#207]
I get this error from rails:

```
TypeError in MyController#index
no _dump_data is defined for class Proc
```

I'm reporting it here because the error is gone when I comment out this line:

```
    @token = @client.auth_code.get_token(
      params[:code], 
      :redirect_uri => ..., 
      :headers => {'Authorization' => 'Basic some_password'},
    )
```

The @client is set up like this:

```
    @client = OAuth2::Client.new(client_id, client_secret, {
      :site           => ..., 
      :token_url      => ..., 
      :authorize_url  => ..., 
      :raise_errors   => false
    })
```

Anyone else having this issue?

**Comment by xtagon** [comment]
@filkaris Are you still able to reproduce this issue on the latest version?

**Comment by pboling** [comment]
`_dump_data` never appears in the code in this project.  I am 99.9% certain this error is related to something else you had in your code.
