### ISSUE TITLE
Method for revoking an access token

### ISSUE THREAD

**Issue by bsteephenson** [oauth-xx/oauth2#244]
It would be cool if there were a method on AccessToken for revoking by calling POST /oauth/revoke

**Comment by arantir** [comment]
:+1: 

FYI http://tools.ietf.org/html/rfc7009

**Comment by johaywood** [comment]
@intridea-shared is this something you would be open to a PR for? I'd find this feature helpful as well.

**Comment by xtagon** [comment]
@johaywood A PR would be welcome!

**Comment by pboling** [comment]
#244 is the same issue, and was opened first.  Closing.
