### ISSUE TITLE
New gem release?

### ISSUE THREAD

**Issue by agrobbin** [oauth-xx/oauth2#246]
Since e0006cb5099bf392f011eb5c49cbec4f893bbdba was pushed to `master` on 2/17, it'd be great if v1.1.1 could be cut and pushed to RubyGems. We'd love to be able to use the latest and greatest `jwt` but can't without depending on the master branch of this gem.

``` ruby
# Gemfile
gem 'oauth2', github: 'intridea/oauth2'
```

Thanks!

**Comment by connorshea** [comment]
This would be really nice!

**Comment by connorshea** [comment]
@sferik any chance of this happening? We need it for GitLab as I'm updating gems to be compatible with Rails 5 in preparation of its release, and 1.1.0 causes our jwt version to be downgraded.

**Comment by connorshea** [comment]
Rais 5.0.0.rc1 was released today: https://github.com/rails/rails/releases/tag/v5.0.0.rc1

Wanted to follow-up and see if there was any chance of a new gem release?

**Comment by sferik** [comment]
Hi all. I’m planning to ship a new gem release in the next couple of days.

**Comment by connorshea** [comment]
Excellent, thank you :)

**Comment by connorshea** [comment]
@sferik don't want to a bother, just poking you to see if there's anything blocking this?

**Comment by marten** [comment]
I'm currently tracking a git commit rather than the published gem solely because of the JWT dependency. Would at least a minor release from that commit be possible short-term?

**Comment by connorshea** [comment]
@sferik Bumping since [Rails 5 has been released today](http://weblog.rubyonrails.org/2016/6/30/Rails-5-0-final/). Any news on a new RubyGems release? :)

Thank you for the work on the gem!

**Comment by sferik** [comment]
I just shipped version 1.2.0! Go nuts! :shipit:

**Comment by connorshea** [comment]
@sferik :Tada: thank you!

**Comment by pboling** [comment]
We will be shipping a the new new soon, after a bit more PR and issue triage.  Closing this as an old issue.
