### ISSUE TITLE
get_token gives error on MS Chart endpoint but seems to have result

### ISSUE THREAD

**Issue by rept** [oauth-xx/oauth2#254]
Hi,

I'm trying to get a token for this end point:

```
client = OAuth2::Client.new('60f5e108-c59a-4b96-xxxx-xxxxxxxxxxxx', 'ZZZZZZZZZZTkr4oVdE5pGrY', :site => 'https://login.microsoftonline.com',
  authorize_url: "/common/oauth2/v2.0/authorize",token_url: "/common/oauth2/v2.0/token",:scope => SCOPES.join(' '))
```

When requesting the token with this command:

```
client.auth_code.get_token(auth_code,:redirect_uri => @redirect_url,:scope => SCOPES.join(' '))
```

I get an error:

```
: {"token_type":"Bearer","id_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1uQ19WWmNBVGZNNXBPWWlKSE1iYTlnb0VLWSJ9.eyJhdWQiOiI2MGY1ZTEwOC1jNTlhLTRiOTYtODIxYS03YWM1ZTU0ZTNhZDYiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vNWFmYTRmNDMtMzA5Yy00MTA3LTllMTktMWIzMGQ3MTA4NmIzL3YyLjAiLCJpYXQiOjE0NjQwNDA1NTEsIm5iZiI6MTQ2NDA0MDU1MSwiZXhwIjoxNDXXXXXXXXXXXX"}
```

This is the exact error message (except for the XXXXX on the end) I'm getting.  I'm able to parse the id_token in https://jwt.io/ and it decodes this.  I'm seeing aud, iss, iat, nbf, exp, ...  

When I debug in the client.rb I see in the request method the response.status equals 200.

Any ideas?  (I'm using oauth2 (1.1.0))

**Comment by rept** [comment]
Finally found the cause!

It's mentioned here:
https://github.com/intridea/oauth2/pull/243

Any plans on getting it merges?

**Comment by xtagon** [comment]
@rept 
> Any plans on getting it merges?

We have new maintainers now and are getting things organized again. If you still would like it merged, let us know on that issue. There are conflicts since it's been a while.

**Comment by pboling** [comment]
It did get merged!
