### ISSUE TITLE
response.parsed is not a hash

### ISSUE THREAD

**Issue by lufeihaidao** [oauth-xx/oauth2#258]
![image](https://cloud.githubusercontent.com/assets/1731864/16294221/023ae01a-3952-11e6-85fa-3972c80aad64.png)

in client.rb, `response.parsed` is not a hash.

**Comment by lufeihaidao** [comment]
It's from weibo api. If it's from github api, response.parsed is a hash.

**Comment by joaovitoras** [comment]
🆙

**Comment by joaovitoras** [comment]
@lufeihaidao Did you get any solution?

**Comment by joaovitoras** [comment]
@lufeihaidao read this https://github.com/mkdynamic/omniauth-facebook/issues/204.
Add `token_params: { parse: :json }` to you provider or update omniauth-facebook to v4.0.0

**Comment by tak1n** [comment]
Having the same problem getting back something like:

```
[15] pry(#<OAuth2::Client>)> response.parsed
=> {"{\"access_token\":\"xxx\",\"token_type\":\"bearer\"}"=>
  nil}
```

Upgrading to omniauth-facebook v4.0.0 like @joaovitoras suggested worked out for us, thx for sharing that :)

**Comment by jhollinger** [comment]
To anyone who's using `OAuth2::Client` directly (w/o `omniauth`), the fix looks more like this:

    client.auth_code.get_token(params[:code], parse: :json, redirect_uri: "...")

**Comment by xtagon** [comment]
Closing because workarounds have been given. We can open again if this is still an ongoing issue
