### ISSUE TITLE
Retrieving authorization_code

### ISSUE THREAD

**Issue by yijia-zhan** [oauth-xx/oauth2#259]
For the `authorization code` workflow, it seems that the gem only make a token request (to the token endpoint `/oauth/token`) with the `auth_code`. But it doesn't seem to provide an API where user (of the gem) can use to retrieve `authorization_code`. Is the intended? I'm curious the reason behind this.

Basically, if I want to implement the `authorization_code` workflow with the gem, I need to implement my own way of fetching `auth_code`? then pass the code into the gem's api to fetch `access_token`? Is this the assumption?

**Comment by galois17** [comment]
@yijia-zhan , that's how the authorization flow works. The callback (or redirect) url that the user-agent (or browser) is sent to will have the authorization code. You can read more about the flow here [https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2](url).
