### ISSUE TITLE
request to follow SemVer/mention it in README

### ISSUE THREAD

**Issue by pravi** [oauth-xx/oauth2#262]
Do you follow Semantic Versioning http://semver.org? If yes, can this be mentioned in README? If not, can you consider it?

**Comment by pravi** [comment]
@technoweenie can you reply?

**Comment by technoweenie** [comment]
Sure, Semver would be nice :+1: But I also don't maintain this gem :)

**Comment by xtagon** [comment]
@pboling What are your thoughts? I am for it.

**Comment by pboling** [comment]
I am absolutely in favor of [SemVer 2.0](https://semver.org/spec/v2.0.0.html) going forward, and will add a mention to the Readme.  It has become an invaluable tool with the advent of services like Depfu.

@technoweenie do you happen to know how to get in contact with @sferik or @mbleigh to transfer ownership of the gem on RubyGems.org?  We can't release a new version until we get access there.
