### ISSUE TITLE
Adding OAuth to Gemfile in Ruby 2.1.4 requires Ruby 2.2.2

### ISSUE THREAD

**Issue by milesmatthias** [oauth-xx/oauth2#264]
When I add OAuth2 ~> 1.2 to a Gemfile under Ruby 2.1.4 and bundle install, I get an error saying that it can't install Rack because Rack requires Ruby 2.2.2.

The README of OAuth2 says it supports 2.1.4.

**Comment by milesmatthias** [comment]
It works in Ruby 2.1.4 with OAuth 2 v1.0.0.

**Comment by pboling** [comment]
Thanks for the report.  We need to determine what the Ruby requirement is, and document it prior to the next release.

**Comment by xtagon** [comment]
Related to https://github.com/oauth-xx/oauth2/issues/332

**Comment by pboling** [comment]
@milesmatthias this should be fixed in master.  If you are able to try it out, and report back it would be great!
