### ISSUE TITLE
redirect uri incompatible with Doorkeeper

### ISSUE THREAD

**Issue by SophieDeBenedetto** [oauth-xx/oauth2#265]
There seems to be an issue when building out a custom OmniAuth strategy to be used when authenticating with an application that uses Doorkeeper. 

After first request for authorization request is completed and authorization code is returned, the redirect URI has that code and the status appended to it. 

![oauth-note](https://cloud.githubusercontent.com/assets/8999596/17306212/d0238b12-57fc-11e6-8674-ca798f86cf2c.png)

When the subsequent request to the token URL is made, Doorkeeper seems to be unable to recognize the altered redirect URI as valid and the following error is thrown: 

![screen shot 2016-08-01 at 3 22 12 pm](https://cloud.githubusercontent.com/assets/8999596/17306249/f9bcbeb2-57fc-11e6-9777-0e3219698c80.png)

I don't think that this is an issue with my custom OmniAuth strategy. You can find the source for that strategy, bundled as a gem [here](https://github.com/flatiron-labs/omniauth-learn) and for a quick look at how that strategy is defined:

``` ruby
require 'omniauth-oauth2'

module OmniAuth
  module Strategies
    class Learn < OmniAuth::Strategies::OAuth2
      include OmniAuth::Strategy

      option :client_options, {
               site: "https://learn.co",
               authorize_url: "https://learn.co/oauth/authorize",
               token_url: "https://learn.co/oauth/token"
             }

      def request_phase
        super
      end

      info do
        raw_info.merge("token" => access_token.token)
      end

      uid { raw_info["id"] }

      def raw_info
        @raw_info ||= access_token.get('/api/users/me').parsed
      end
    end
  end
end
```

By checking to see if the request being made was the secondary request to the token URL, and changing the redirect URI to remove the appended authorization code and status if so, has fixed the problem for me. I created a fork of OAuth2 and my fix can be found [here](https://github.com/flatiron-school/oauth2/commit/bf389481ec02f65aa2885a787dbbad342af084a3).

I did some googling, and found a number of other people who encountered the same issue when building a custom OmniAuth strategy, authorizing with a service that uses Doorkeeper to handle OAuth. 

If this is in fact an incompatibility with Doorkeeper, I would recommend incorporating this change into OAuth2, as Doorkeeper is a fairly common library for handling OAuth in Rails.

**Comment by dankozlowski** [comment]
I've run in to this issue as well, any hope in pushing that PR forward?

**Comment by COConsulting** [comment]
Is this still an active request?

**Comment by pboling** [comment]
This code is now very different from what is in `master`.  Closing.  If this is still an issue, please comment!
