### ISSUE TITLE
OAuth2::Error: unauthorized: Full authentication is required to access this resource

### ISSUE THREAD

**Issue by jaimeneto85** [oauth-xx/oauth2#274]
`
def get_token client_id, api_key, url_get_token, my_site, base64 
    client = OAuth2::Client.new(client_id, api_key , site: url_get_token)
    client.auth_code.authorize_url(redirect_uri: my_site)
    @token_id = client.auth_code.get_token('client_credentials_value', headers:{ 'Authorization' => " Basic #{base64}"})
end`

I did this steps, but when I call get_token I receive this:
OAuth2::Error: unauthorized: Full authentication is required to access this resource
{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}

could you help me?

**Comment by jaimeneto85** [comment]
I created this issue because this error means that the headers is not working

**Comment by pboling** [comment]
Version 2 has been released, and lots of things have changed.  Please reopen if this continues to be a problem on version 2.
