### ISSUE TITLE
Bump Rack version to 2.0. Pull request created #278 but has issues. Request for comments

### ISSUE THREAD

**Issue by tiabas** [oauth-xx/oauth2#279]
The version of Rack in the Gemfile is ~> 1.2 whereas in the gemspec it is `[>=1.0, <3]`. For projects relying on this gem but requiring `rack ~> 2.0`, `bundle install`  fails because it builds agains the version in the Gemfile.

I am seeing this issue with a Rails 4.2 to rails 5.0 migration where by Rails 5 depends on `rack ~> 2.0` but the `omniauth` gem relies on `oauth` gem which has a definition of `rack ~> 1.2`. 

To further complicate matters, `rack 2.0` requires a minimum ruby version `ruby => '2.2.2'`. I have a pull request https://github.com/intridea/oauth2/pull/278 to update the rack version. However that is failing in travis.

I would appreciate advice on how to go about fixing this. Thanks!

**Comment by leoarnold** [comment]
Is this still an issue? [Build 524](https://travis-ci.org/oauth-xx/oauth2/builds/347030828) passed with

```
gemfiles/jruby_1.7.gemfile:gem "rack", "~> 1.2"
gemfiles/ruby_1.9.gemfile:gem "rack", "~> 1.2"
gemfiles/ruby_2.0.gemfile:gem "rack", "~> 1.2"
gemfiles/ruby_2.1.gemfile:gem "rack", "~> 1.2"
oauth2.gemspec:  spec.add_dependency 'rack', ['>= 1.2', '< 3']
```

**Comment by pboling** [comment]
@JJJJust is correct.  @leoarnold it should not be an issue.  I overhauled the gem's dependency structure recently.

Closing.
