### ISSUE TITLE
This Hotel Is Under New Management!  Inquire Within.

### ISSUE THREAD

**Issue by wy193777** [oauth-xx/oauth2#307]
There are some good pull requests hanging there without any comments. Maybe it's a time for a new fork?

**Comment by josephpage** [comment]
@sferik ?

**Comment by wy193777** [comment]
I original developer maintain this project has gone so no one in intridea cares it now.

**Comment by josephpage** [comment]
This is annoying.
oauth2 is probably critical for many businesses, and no one can review&merge security fixes or just future evolutions.
For example, many Omniauth strategies are based on [omniauth-oauth2](https://rubygems.org/gems/omniauth-oauth2), which is based on intridea/oauth2. Many official API clients for developer services are oauth2-based too.

This gem deserves a future, a governance, a team, and a maintainer ! 🙏 

I guess @sferik and @mbleigh should organize the transfer to a team of volunteers, or maybe to the team of other gem(s) that has a significant interest in oauth2.

**Comment by athix** [comment]
+1 on this, [Sorcery](https://rubygems.org/gems/sorcery) currently uses intridea/OAuth2 for its oauth providers as well.

**Comment by xtagon** [comment]
Hi everyone,

@pboling and a few others in the community, including me, are working to take over ownership of this repository and step up to maintain it. I'm sure there will be a transition period as while things get settled, but lots of projects depend on this gem so we're not gonna let it die :)

**Comment by pboling** [comment]
We have moved the gem to oauth-xx organization, and are definitely interested in having more contributors.  This must be a community effort.  None of the maintainers have a lot of free time, which means we need more maintainers to keep things humming.

We've merged a few PRs, but I still haven't been pinged back by the gem owners on RubyGems.org, @sferik or @mbleigh ... If anyone knows a way to get in touch with them it would be great.  Email and github mentions are not working.

**Comment by josephpage** [comment]
Hey @pboling and @xtagon 
Thank you very much for your action !
The gem is critical to my business at Labacar. We use the gem to connect to many data & service providers (including some real-time telematics systems).

I'm interesting being a maintainer.
In particular, my organization needs me to be involved in the following aspects:
  - systematic tests with every new Ruby/Rails environments
  - strict compliance with RFC without compromising ease of use
  - global performance and memory footprint

**Comment by pboling** [comment]
@josephpage I would like to get a release out that allows use of the latest version of faraday ASAP.  We are definitely looking for new maintainers.  If you can do some PR reviews, and issue triage to prove your interest, I will be happy to add you as a maintainer.

I was able to get in touch with @mbleigh and should now have the ability to push a new version of the gem to RubyGems.

**Comment by xtagon** [comment]
I propose we start using labels in the issue tracker to help with prioritizing - lots of people including me want to contribute but we're starting fresh with a bunch of existing issues to weed through.

**Comment by pboling** [comment]
@xtagon are you able to manage labels on this project, or do you need more permissions?

**Comment by xtagon** [comment]
@pboling Looks like I am able to. I'll add some tonight.

**Comment by xtagon** [comment]
Created some labels, and I went though quite a lot of open issues to tag or close them. There are way more issues than I thought so I didn't get them all - if anyone wants to do the same it would help out a lot. Many of the issues haven't had activity in years, but there's still important ones.

**Comment by pboling** [comment]
I hope to go through some soon.

**Comment by josephpage** [comment]
I also went through a few issues.
I have added the `docs`, `need-docs` and `need-spec` labels.

**Comment by johaywood** [comment]
Hi team. Commented on another issue, but should probably bring it here. I'd be interested in taking a more official maintainer role on this project. I've relied heavily on this project, and continue to do so. Seeing how important this project is to so many people, I definitely don't want to let it die. I know you're working on a 1.5.0 release -- where can I jump in to help get it over the finish line?

**Comment by pboling** [comment]
- go through the issues and PRs, label, comment, investigate, etc.
- help us determine what to address, what is critical
- assist in preparing changelog for release, and evaluating what are breaking changes
- using the master branch on your own project to dog food it

I will add you as a maintainer.  Your contributions on issues and PRs, and knowledge of the way the gem works, is apparent. 👍

**Comment by johaywood** [comment]
@pboling awesome! Definitely a worthy cause to get this project back into good shape, and keep it that way.

**Comment by pboling** [comment]
For people coming here that may not see discussions elsewhere, the next release will be *2.0.0* (not 1.5.0).  This is because it will contain some breaking changes, all of which will be documented in the [CHANGELOG](https://github.com/oauth-xx/oauth2/blob/master/CHANGELOG.md), which work is in progress [in this PR here](https://github.com/oauth-xx/oauth2/pull/335).

The 2.0.0 release will not drop support for any Rubies (and in fact will officially list some new supported old Rubies).

Dropping support for currently supported Rubies below 2.2 will happen in the following major release, 3.0.0.

**Comment by pboling** [comment]
Closing this issue for now.  New maintainers are still welcome.  Jump in with a pull request, or insightful code reviews.

**Comment by vbrazo** [comment]
I wanna be part of this project to learn how this gem works behind the scenes. I'll take a look at the issues and PRs. Thanks for letting us contribute.
