### ISSUE TITLE
Support faraday 0.13

### ISSUE THREAD

**Issue by Keruspe** [oauth-xx/oauth2#315]
Currently the gemspec specifies that farafay must be < 0.13 whilst last version is 0.13.1

**Comment by jrochkind** [comment]
It's pretty annoying that using oauth2 limits to you to an old faraday without bug fixes. Is there any reason the gemspec is not allowing 0.13 or later?  

https://github.com/intridea/oauth2/blob/master/oauth2.gemspec#L8

**Comment by pboling** [comment]
Would like to be able to use this fix in latest faraday release:
https://github.com/lostisland/faraday/issues/701

Why is there a hard dependency like this in the first place?

**Comment by jcoyne** [comment]
For those wondering about why this is so conservative, it may be because Faraday is < 1.0 and they have made breaking changes in the past.  I don't maintain this library, but other libraries I have used have been bitten when there was a new 0.x release of Faraday.

**Comment by pboling** [comment]
That is reasonable, good insight.  It seems that Intridea is letting this gem rot looking at the number of outstanding PRs that have gotten no feedback from maintainers.

@intridea - Do you need more maintainers on this gem?  A lot of people, including myself, depend on this gem.

**Comment by xtagon** [comment]
@pboling I depend on this gem too and am willing to help contribute, but I can't commit to doing it steadily.

There is a notice on the README that says who to contact if you are interested in taking over the gem: https://github.com/intridea/oauth2#omniauth-is-looking-for-a-new-home--if-you-are-interested-in-taking-over-this-project-please-contact-jasonmobomocom

Maybe we can work together and at least keep things up to date?

**Comment by pboling** [comment]
@xtagon Yes.  Let's do it.  I can also only contribute part-time, but it would be far more than nothing.  I will contact Jason.

**Comment by xtagon** [comment]
@pboling Sounds great! Feel free to get in touch with me after you hear from Jason and we'll make a plan.

**Comment by pboling** [comment]
@xtagon I emailed Jason and never heard back.  I will try other modes of contact soon.
