### ISSUE TITLE
Support Newer JWT Rubygem

### ISSUE THREAD

**Issue by mufid** [oauth-xx/oauth2#319]
Our project needs `jwt ~> 2.0` for security reason, but our project also use OAuth2, which depends to `jwt ~> 1.0`

Could we release a rubygem with jwt 2.0 version?

Thanks!

**Comment by risa** [comment]
+1 

Thanks!

**Comment by dnd** [comment]
+1

**Comment by RomainMorlevat** [comment]
Same thing here.

**Comment by pboling** [comment]
Please submit a PR.  None of the maintainers have very much extra time.  Whoever is feeling the most pain here, please stand up.

**Comment by RomainMorlevat** [comment]
@pboling 
In fact, there is already a PR, submitted about a month before this issue :
[https://github.com/oauth-xx/oauth2/pull/317](https://github.com/oauth-xx/oauth2/pull/317)

**Comment by pboling** [comment]
Thanks for pointing it out!  I haven't been able to go through the backlog of PRs yet.  Just took over maintenance of the gem a week ago.

**Comment by pboling** [comment]
This is now done in master.
