### ISSUE TITLE
client_credential auth deliberately drops refresh_token on the ground

### ISSUE THREAD

**Issue by ahoward** [oauth-xx/oauth2#321]
the code is very clear:

- https://github.com/intridea/oauth2/commit/6d1234beacbffb73fb8f015119d9347953dd6f95#diff-f7b21fa7962f1a60aacaf0cbf0e4561cR20  # dropping refresh

tests assert this:

- https://github.com/intridea/oauth2/commit/6d1234beacbffb73fb8f015119d9347953dd6f95#diff-4e2f0aa719bf795eb99a02a52e310f3bR46

but, strangely, the spec says both can be returned:

- ![](https://cl.ly/mybW/Image%202017-10-09%20at%208.20.19%20PM.png)

- https://tools.ietf.org/html/draft-ietf-oauth-v2-22#section-1.5

the PR for this is simple but why on earth is the refresh token being deliberately nuked?

ps.  i think a bunch of other token related issues stem from this bug, eg

- https://github.com/intridea/oauth2/issues/213
- https://github.com/intridea/oauth2/issues/122

**Comment by matt-glover** [comment]
I think that is following the spec for the client credentials flow specifically. From the same spec linked above take a look at the [client credentials section](https://tools.ietf.org/html/draft-ietf-oauth-v2-22#section-4.4) in the [Access Token Response subsection](https://tools.ietf.org/html/draft-ietf-oauth-v2-22#section-4.4.2). It says the refresh token should not be included in the response:
> 4.4.3.  Access Token Response
> 
>    If the access token request is valid and authorized, the
>    authorization server issues an access token as described in
>    Section 5.1.  A refresh token SHOULD NOT be included.

Many of the other auth flows do indicate a refresh token is allowed per the spec.

**Comment by pboling** [comment]
Any ideas on how we could support both?

**Comment by pboling** [comment]
Closing this in favor of #528, will fix it.
