### ISSUE TITLE
How to refresh token automatically ?

### ISSUE THREAD

**Issue by Aornn** [oauth-xx/oauth2#327]
Hi ! 
I would know how to refresh my token automatically and transparently for the user (i use it for rails)
do you have any idea ?
thanks

**Comment by josephpage** [comment]
Hey @Aornn,
Here is a example of you can refresh tokens automatically inside an ActiveRecord model : 
```ruby
class ApiConnection < ApplicationRecord
  attr_encrypted :credentials, key: KEY, marshal: true

  # check access token validity and return a ready-to-use client
  def api
    access = tokens
    access.expired? ? refresh_tokens : access
  end

  # build the token from the credentials field
  def tokens
    @tokens ||= OAuth2::AccessToken.from_hash(
      client,
      self.credentials['token'].clone
    )
  end

  # refresh the access tokens and store it in the database row,
  # avoiding concurrent access with a database lock
  def refresh_tokens
    with_lock do
      new_token = tokens.refresh!
      self.credentials = self.credentials.merge({ 'token' => new_token.to_hash })
      self.save!
    end
    new_token
  end

  # initializing the Oauth2 client
  def client
    @client ||= OAuth2::Client.new(CLIENT_ID, APP_SECRET)
  end
end
```
Then you can do : 
`ApiConnection.first.api.get('/v1/profile')`
or 
`ApiConnection.first.api.post('/v1/users', body: {}.to_json)`

Always use "ApiConnection#api" directly to be sure the access token is valid for every requests.

This example works for refresh of both `access_token` and `refresh_token`. (The RFC says the refresh_token should be renewed on each renewal of access_tokens, but some major Oauth2 users/provides like Google or FB don't follow this rule)
