### ISSUE TITLE
Travis CI, Gemnasium, and CodeClimate need to point to the new repo

### ISSUE THREAD

**Issue by xtagon** [oauth-xx/oauth2#333]
The following badges in the documentation are currently broken due to the repo move:

- https://travis-ci.org/intridea/oauth2
- https://gemnasium.com/oauth2
- https://codeclimate.com/github/intridea/oauth2

**Comment by josephpage** [comment]
Not only the badge, but also the tests on new PRs are broken too.
We need to recreate new accounts for each service with the new organization "oauth-xx".

**Comment by pboling** [comment]
https://travis-ci.org/oauth-xx/oauth2 is ready

**Comment by pboling** [comment]
i wasn't able to get Gemnasium to refresh my repo list so I can add it there.  Fortunately depfu is awesome and does all the things Gemnasium does, and I was able to add it there.

**Comment by pboling** [comment]
Also having trouble with granting access to this repo on CodeClimate 👎

**Comment by josephpage** [comment]
Depfu is a very good idea. Do they have a badge to proudly display that the gem is up to date ?

The Coveralls badge seems to work but the integration is broken.

**Comment by pboling** [comment]
A badge is the only thing Gemnasium has that Depfu doesn't. :(

**Comment by josephpage** [comment]
Travis builds also use a Coveralls account.

**Comment by xtagon** [comment]
Thanks @pboling and @josephpage. #334 closes this.
