### ISSUE TITLE
Would you please update gem on rubygems.org

### ISSUE THREAD

**Issue by larryzhao** [oauth-xx/oauth2#348]
Hi, guys, 

`oauth2 1.4.0` on rubygems.org still lock `jwt` to `~> 2.1.0`. But on master branch，the dependency already changed to `>= 1.0 < 3.0`。

Would you please release a version 1.4.1 to rubygems.org ?

Thanks & Best Regards.

**Comment by pboling** [comment]
We are working on a version 1.5.0 right now.  Bumping a version of a dependency makes the change not necessarily backwards compatible, and we are following semver: https://semver.org/

**Comment by larryzhao** [comment]
OK, Thanks. Looking forward to 1.5.0
