### ISSUE TITLE
jwt ~> 1.0 constraint is causing issues updating other gems

### ISSUE THREAD

**Issue by thewoolleyman** [oauth-xx/oauth2#416]
the jwt gem is now at 2.1.0.  The latest release of oath2, 1.4.0, locks jwt to ~> 1.0, which is preventing other gems with dependencies on jwt from being updated.

Is there any reason you can't you make a release of oath2 1.x which allows jwt 2.x?  If not, why not?

Alternately, how far away is a beta release of oauth2 2.x?

Thanks,
-- Chad

**Comment by pboling** [comment]
You can try doing that.  `master` has moved beyond 1.4 and is now a veritable pre-2.0.  I will create a 1.4-stable branch, using the exact commit that was then current when the gem was last released, and then you would off of that for a PR to the same.

**Comment by pboling** [comment]
@thewoolleyman I have created a [1-4-stable](https://github.com/oauth-xx/oauth2/tree/1-4-stable) branch.  Please use it as the basis for any changes to be released in the 1.4.x line.  There should not be any breaking changes included *at all*.

**Comment by thewoolleyman** [comment]
Cool, here's the PR just to relax the jwt constraint.  Thanks for looking into this so quickly!

**Comment by pboling** [comment]
@thewoolleyman [1.4.1 has been released](http://www.railsbling.com/oauth2/oauth2-1.4.1/)
