### ISSUE TITLE
How to handle a read timeout?

### ISSUE THREAD

**Issue by rpr5x** [oauth-xx/oauth2#435]
I am working on a project that requires me to make OAuth API calls to an external website. Each API call returns 100 entries of data at a time. My setup looks roughly like the following:

```ruby
client_id = ''
client_secret = ''
client = OAuth2::Client.new(client_id, client_secret, site: '')
access_token = client.client_credentials.get_token(client_id: client_id, client_secret: client_secret)
response = access_token.get("/data?page=X&size=100")
```

For the last line, `page` is an integer between 1 and a very large number. The issue is that sometimes the last line that executes the GET request returns a `Net::ReadTimeout` error because the returned data is very large (it could also be due to my slow internet connection as well). This happens for a few values of `page` but not consistently (e.g. if the API call times out for page 1 the first time it was tried, it may not necessarily time out on subsequent tries). Is there a way to specify a larger read timeout to prevent this error from occurring?

**Comment by meganemura** [comment]
We have :connection_opts option for OAuth::Client. It will pass to the faraday connection.
So you can use :timeout faraday option.

**Comment by ruslan-ryzhkov** [comment]
Can you provide an example of how to do this successfully? When I try the following code, I end up with a deprecation warning and an error when executing the last line:

```ruby
client_id = ''
client_secret = ''
client = OAuth2::Client.new(client_id, client_secret, site: '', connection_opts: { timeout: 300 })
access_token = client.client_credentials.get_token(client_id: client_id, client_secret: client_secret)
```

The last line gives me the following warning and error when I try to run it in the rails console:
```ruby
/usr/local/bundle/gems/faraday-0.12.2/lib/faraday/options.rb:50: warning: Object#timeout is deprecated, use Timeout.timeout instead.
Traceback (most recent call last):
        1: from (irb):22
ArgumentError (wrong number of arguments (given 0, expected 1..3))
```

If it helps, I am using version 1.4.0 of the `oauth2` gem and version 0.12.2 of the `faraday` gem.

**Comment by ruslan-ryzhkov** [comment]
I think I figured it out. I used the following format instead, which looks to have worked successfully:

```ruby
client = OAuth2::Client.new(client_id, client_secret, site: '', connection_opts: { request: { timeout: 300 } } )
```

If this is correct, feel free to close this issue. It would be helpful to add a section about this to the README however.

**Comment by rpr5x** [comment]
I think I figured it out. I used the following format, which looks to have worked successfully:

```ruby
client = OAuth2::Client.new(client_id, client_secret, site: '', connection_opts: { request: { timeout: 300 } } )
```

If this is correct, feel free to close this issue. It would be helpful to add a section about this to the README however.

**Comment by anvox** [comment]
I added this doc to wiki [Slow Oauth provider](https://github.com/oauth-xx/oauth2/wiki/Advanced-usage#slow-oauth-providers) Will close after recheck it. Thanks.

**Comment by anvox** [comment]
Verified config works with faraday default adapter.
