### ISSUE TITLE
Client credential: unsupported client authentication method

### ISSUE THREAD

**Issue by kumartushar** [oauth-xx/oauth2#445]
When executing below code block:
```
require 'oauth2'
client = OAuth2::Client.new("my_client_id", "my_client_secret", :site => "my_site_url", :token_url => "oauth2/token")
client.client_credentials.get_token
```

it gives the below error:

```
OAuth2::Error (invalid_client: Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method))
    {
      "error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)",
      "error_hint":"The OAuth 2.0 Client supports client authentication method "client_secret_basic", but method "client_secret_post" was requested. 
      You must configure the OAuth 2.0 client's "token_endpoint_auth_method" value to accept "client_secret_post".","status_code":401
    }
```

I checked the using 'net/http' library, and my `client_id` & `client_secrets` are valid and working.

The only problem I see is with the authentication method as said in hint of above message,

    The OAuth 2.0 Client supports client authentication method "client_secret_basic", but method "client_secret_post" was requested. You must configure the OAuth 2.0 client's "token_endpoint_auth_method" value to accept "client_secret_post"

I checked through the code for - 
1. How can I specify client_secret_basic as client authentication method OR
2. How can I specify token_endpoint_auth_method to accept "client_secret_post"

But I did not find anything for this. Is this something we need to add to gem?

**Comment by pboling** [comment]
@kumartushar I haven't looked into it yet, but have you tried this already?  Based on the error, I think this might work:
```
client = OAuth2::Client.new(
  "my_client_id", 
  "my_client_secret", 
  site: "my_site_url", 
  token_url: "oauth2/token",
  token_endpoint_auth_method: "2\. client_secret_post"
)
```

**Comment by pboling** [comment]
@kumartushar We've had multiple recent pull requests that have added new schemes for getting access tokens, which I think is what you are looking for.  Check this one out, and see if it makes sense to you, and then perhaps submit a PR.

https://github.com/oauth-xx/oauth2/pull/495
