### ISSUE TITLE
Client `fetch_token` throwing `NoMethodError`

### ISSUE THREAD

**Issue by joaolrpaulo** [oauth-xx/oauth2#459]
I am currently using this library to fetch tokens from a centralized identifier service.

The problem occurs when the identifier service is unreachable and we are passing the `:raise_errors` option set to `false`.

The `fetch_token` method throws `NoMethodError` while trying to perform the [following code](https://github.com/oauth-xx/oauth2/blob/c3c49a05ad17bb89aa43df35ec66e30f523667ae/lib/oauth2/client.rb#L225): `response.parsed.merge(access_token_opts)`, because the `response.parsed` is nil.

**Comment by pboling** [comment]
Great analysis.  Do you think you could work up a failing spec in a PR?

**Comment by joaolrpaulo** [comment]
Already did, #460

**Comment by joaolrpaulo** [comment]
Already closed for sometime
