### ISSUE TITLE
Using oauth2 gem with Rails authorize_url seems to get changed

### ISSUE THREAD

**Issue by ghost** [oauth-xx/oauth2#470]
Hi

Beginner question so apologies if obvious....

I am trying to authenticate using oauth2 against a 3rd party API.

I am using the ruby gem oauth2 - https://github.com/oauth-xx/oauth2

The "authorize_url" method insists on adding an oauth subfolder to my URL.

So I want this: https://oauth.companyname.com/authorize?

But I get: https://oauth.companyname.com/oauth/authorize?

    client_id = "Demo"

    client_secret = "blablabla"

    site_path = 'https://oauth.companyname.com'

    client = OAuth2::Client.new(client_id, client_secret, :site => site_path)

    client.auth_code.authorize_url

Why is this happening and how can I solve it please?

**Comment by pboling** [comment]
@Simonp27 Are you using the current master, or the latest released gem?  Please test again latest master.  We are getting close to a 2.0 release, and there are many unreleased fixes in master.

**Comment by jallen92** [comment]
An absolute URL should do the trick. https://github.com/oauth-xx/oauth2/issues/79

```
site_path = 'https://oauth.companyname.com'
auth_url = 'https://oauth.companyname.com/authorize'

client = OAuth2::Client.new(client_id, client_secret, :site => site_path, :authorize_url => auth_url)
```

Also, if needed, you can use an absolute URL for your token_url too.

**Comment by pboling** [comment]
Thanks for the assist @jallen92 !
