### ISSUE TITLE
JRuby TravisCI runs are failing

### ISSUE THREAD

**Issue by dfockler** [oauth-xx/oauth2#473]
Some of the JRuby TravisCI builds are failing to even get to the point where they run the test suite. https://travis-ci.org/oauth-xx/oauth2/jobs/587262107

**Comment by pboling** [comment]
We need to restrict the gem versions (particularly of bundler) per each version of Ruby to fix the builds.

**Comment by pboling** [comment]
I am working on this against the 1.4-stable branch right now, here: https://github.com/oauth-xx/oauth2/pull/478
