### ISSUE TITLE
OAuth2::Error is not really helpful

### ISSUE THREAD

**Issue by jozefvaclavik** [oauth-xx/oauth2#474]
Hey

I tried to do simple token refresh stubbing today, but the lib made it tough.

```
client = OAuth2::Client.new(
  'CLIENT_ID',
  'CLIENT_SECRET',
  authorize_url: 'https://appcenter.intuit.com/connect/oauth2',
  site: 'https://appcenter.intuit.com/connect/oauth2',
  token_url: 'https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer'
)

token = OAuth2::AccessToken.new(
  client,
  'ACCESS_TOKEN',
  refresh_token: 'REFRESH_TOKEN'
)
```

You can ignore those URLs. Then I do `token.refresh!` in a test. Here's a brief version of that.

```
RSpec.describe 'quickbooks_online/token', type: :feature do
  before do
    stub_request(:post, "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer").
    with(
      body: {"client_id"=>"CLIENT_ID", "client_secret"=>"CLIENT_SECRET", "grant_type"=>"refresh_token", "refresh_token"=>"REFRESH_TOKEN"},
      headers: {
        'Accept'=>'*/*',
        'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
        'Content-Type'=>'application/x-www-form-urlencoded',
        'User-Agent'=>'Faraday v0.15.4'
      }).
    to_return(
      status: 200,
      body: "{\"token_type\":\"bearer\",\"expires_in\":3600,\"refresh_token\":\"NEW_REFRESH_TOKEN\",\"x_refresh_token_expires_in\":1569480516,\"access_token\":\"NEW_ACCESS_TOKEN\"}",
      headers: {}
    )
  end

  context '#refresh' do
    subject { token.refresh! } # token comes from code above
    
    it { expect(subject.access_token).to eq('NEW_ACCESS_TOKEN') }
  end
end
```

But all I got is this error
```
     OAuth2::Error:
       {"token_type":"bearer","expires_in":3600,"refresh_token":"NEW_REFRESH_TOKEN","x_refresh_token_expires_in":1569480516,"access_token":"NEW_ACCESS_TOKEN"}
```

So stubbing works fine, but whats up with the error? Does it make sense to you?

After digging I came across [this client.rb#L148](https://github.com/oauth-xx/oauth2/blob/v1.4.1/lib/oauth2/client.rb#L148). You just return generic error with response body. Thats not very helpful.

Then after putting bunch of debugger statements I noticed that `response.parsed` returned `nil` But still couldn't figure out why. After going deeper into response class, I noticed that `parser` was `nil`, so it couldn't pick up correct parser. This is where I stopped trying to figure out how oauth2 picks up parser and just tried to set `Content-Type` response header.

```
headers: {
  'Content-Type'=>'application/json'
}
```
And that was it.

I think it would be way better to raise some meaningful error [here response.rb#L70](https://github.com/oauth-xx/oauth2/blob/v1.4.1/lib/oauth2/response.rb#L70) instead of just returning `nil` and then raising generic `OAuth2::Error` with response body.

**Comment by pboling** [comment]
Interesting.

https://stackoverflow.com/questions/40998133/content-type-for-token-request-in-oauth2

What you had initially, `'Content-Type'=>'application/x-www-form-urlencoded'`, is definitely correct, and `'Content-Type'=>'application/json'` is definitely wrong.

Looks like this is possibly a bug.
