### ISSUE TITLE
It isn't possible to change the default @option params

### ISSUE THREAD

**Issue by emersonmoura** [oauth-xx/oauth2#491]
I have a microservice architecture and each microservice has a specific path to be accessed. My oauth2 API has the path `/uaa`. So I tried to change the token_url param to be `/uaa/oauth/token` and I didn't get success also I put my site address with the suffix `/uaa,` however (and according to the semantic) it considers only the domain ignoring the rest.

**Comment by pboling** [comment]
@emersonmoura does the answer given here help?
https://github.com/oauth-xx/oauth2/issues/470#issuecomment-536151669

**Comment by pboling** [comment]
You should remove the leading `/` if you want to use a relative path.
