### ISSUE TITLE
Wiki link not working

### ISSUE THREAD

**Issue by terberes** [oauth-xx/oauth2#502]
Wiki link redirects to blank page saying "We didn't receive a proper request from your browser. Please contact us if the problem persists."

Happens on macOS 1.15.4 with latest Safari, Chrome, Firefox

**Comment by aesyondu** [comment]
I'm just wondering where the docs are, I had to use `pry` and `cd` into `OAuth2::AccessToken` just to identify what method to use to know if a token if expired or not (`expired?` by the way).

**Comment by anvox** [comment]
I usually check rubydoc before open gem's source code. i.e. https://www.rubydoc.info/gems/oauth2/OAuth2/AccessToken 
But agree that we need more documents and examples.

**Comment by anvox** [comment]
Fixed in https://github.com/oauth-xx/oauth2/pull/515. I'm going to update wiki per question issues.

**Comment by anvox** [comment]
Thanks @terberes  I updated wiki link in [README.md](https://github.com/oauth-xx/oauth2#resources)
