### ISSUE TITLE
Cannot get access token with client credentials grant type

### ISSUE THREAD

**Issue by crush-157** [oauth-xx/oauth2#503]
I am trying to get an access token for an OAuth2 server with the grant type client credentials.

I can do this with curl:
```
$ curl -X POST -u "$CLIENT_ID:$CLIENT_SECRET" -d "grant_type=client_credentials" $BASE_URL$TOKEN_URL_SUFFIX
{"access_token":"nFPY_meZ-h3XAOjljqYR4g","token_type":"bearer","expires_in":3600}
```

I then attempt to do the same with the following piece of Ruby code:

```
require 'oauth2'

client_id = ENV['CLIENT_ID']
client_secret = ENV['CLIENT_SECRET']
base_url = ENV['BASE_URL']
token_url_suffix = ENV['TOKEN_URL_SUFFIX']

opts = { :site => base_url, :token_url => token_url_suffix }

client = OAuth2::Client.new(client_id, client_secret, opts)

token = client.client_credentials.get_token
```

When I attempt to run this it fails:
```
$ ruby oauth2.test                                   [15:06:06]
Traceback (most recent call last):
	3: from oauth2.test:12:in `<main>'
	2: from /Users/eslater/.gem/ruby/2.6.3/gems/oauth2-1.4.4/lib/oauth2/strategy/client_credentials.rb:20:in `get_token'
	1: from /Users/eslater/.gem/ruby/2.6.3/gems/oauth2-1.4.4/lib/oauth2/client.rb:147:in `get_token'
/Users/eslater/.gem/ruby/2.6.3/gems/oauth2-1.4.4/lib/oauth2/client.rb:120:in `request': <!DOCTYPE html> (OAuth2::Error)
<html>...(a lot of HTML)
```

There is a lot of HTML, but the most relevant part seems to be:
```
<head>
  <title>Unauthorized</title>
</head>
```

However, as shown above I can get an access token from the same server, with the same credentials using `curl`.

So I would be interested to know if anyone can:
1. Successfully get an access token using `OAuth2::Client#client_credentials.get_token` (if so, what am I doing wrong)?
2. Reproduce this issue?

**Comment by crush-157** [comment]
Having investigated further, it seems that the problem is that the `client_id` and `client_secret` are being passed in the request body *not* using the HTTP Basic authentication scheme.

According to https://tools.ietf.org/html/rfc6749#section-2.3.1:

> Including the client credentials in the request-body using the two parameters is NOT RECOMMENDED and SHOULD be limited to clients unable to directly utilize the HTTP Basic authentication scheme (or other password-based HTTP authentication schemes).

So the credentials should be passed using HTTP Basic since any client using this library *is* able to use HTTP Basic.

**Comment by crush-157** [comment]
OK, this seems to be a problem with the code in the gem not behaving as described in the RDoc.

`gem install oauth2` installed `oauth2-1.4.4` (I just reinstalled and this is still the version that gets installed).

According to `ri` for `OAuth2::Client` that is installed with this version of the gem, `:auth_scheme` should default to `:basic_auth`.

However, the code in `initialize` actually sets `:auth_scheme => :request_body`.

If I explicitly set `:auth_scheme => :basic_auth` when I create the client, I get the behaviour I expect (i.e. the auth token is returned).

If I check the current version of `client.rb` on GitHub (commit bd494ee, 29/01/2020) then the default value of `:auth_scheme` is being set correctly.

So the issue should be resolved by an updated release of the gem.

**Comment by MittchoBaroco** [comment]
Hey @crush-157 

I am using `.client_credentials` and it works fine for me. I would try without `token_url_suffix = ENV['TOKEN_URL_SUFFIX']` as `OAuth2::Client` add `/oauth/token` by default.

**Comment by crush-157** [comment]
@MittchoBaroco tried without `token_url_suffix` and I get the same error.

But if I create a client, this time setting `:auth_scheme => :basic_auth` in `opts` I get a token just fine.

Could you please try the following:
```
bash-3.2$ cd ~/.gem/ruby/2.6.3/gems/oauth2-1.4.4/lib/oauth2
bash-3.2$ cat client.rb | grep :auth_scheme
    # @option opts [Symbol] :auth_scheme (:basic_auth) HTTP method to use to authorize request (:basic_auth or :request_body)
                  :auth_scheme      => :request_body,
      params = Authenticator.new(id, secret, options[:auth_scheme]).apply(params)
bash-3.2$ 
```

Do you see `:auth_scheme => :request_body` ?

Then if you look at the [source](https://github.com/oauth-xx/oauth2/blob/master/lib/oauth2/client.rb) you'll see that `:auth_scheme => :basic_auth`

So if there's a new release of the Gem with the `:auth_scheme` set correctly that should fix it.

**Comment by jrohrbaugh** [comment]
I think I'm having a similar problem...  I'm trying to implement OAuth in our application using client credentials. 

`client = OAuth2::Client.new("my_id", "my_secret", site: "my_url")
token = client.client_credentials.get_token
Traceback (most recent call last):
       11: from bin/rails:4:in `<main>'
       10: from bin/rails:4:in `require'
        9: from /usr/local/bundle/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
        8: from /usr/local/bundle/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        7: from /usr/local/bundle/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:78:in `console'
        6: from /usr/local/bundle/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/console_helper.rb:9:in `start'
        5: from /usr/local/bundle/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/commands/console.rb:65:in `start'
        4: from (irb):268
        3: from /usr/local/bundle/ruby/2.6.0/gems/oauth2-1.4.4/lib/oauth2/strategy/client_credentials.rb:20:in `get_token'
        2: from /usr/local/bundle/ruby/2.6.0/gems/oauth2-1.4.4/lib/oauth2/client.rb:147:in `get_token'
        1: from /usr/local/bundle/ruby/2.6.0/gems/oauth2-1.4.4/lib/oauth2/client.rb:120:in `request'
OAuth2::Error (invalid_client: Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.)
{"error":"invalid_client","error_description":"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."}
`

I've tried a bunch of things and I can't get around the invalid_client error. I tried setting `auth_scheme` to both `basic_auth` and `request_body`, and neither approach fixed it (but I gave a "not implemented" error when I set it to something invalid, so I know it's doing something)

I've been googling the error and found this post: https://backstage.forgerock.com/knowledge/kb/article/a27814899
I don't think it's totally relevant since it pertains to OpenID, but it does suggest a regression bug with OAuth. Is there a way to specify the "Token Endpoint Authentication Method" in this gem, or is that only relevant to OpenID?

**Comment by pboling** [comment]
1. Please try out the latest release of the gem.  Old versions of the 1.x line are not supported, and many bugs have been fixed.

2. As @crush-157 noted, you probably just need to set the `:auth_scheme`!
