### ISSUE TITLE
warning "unexpected middleware set after the adapter. This won't be supported from Faraday 1.0"

### ISSUE THREAD

**Issue by nahzz** [oauth-xx/oauth2#504]
I got this issue when using oauth2 v1.4.1,  while using /master branch this issue is gone.  I think it's because on /master ,  the way how Faraday is built is different compared to v1.4.1  (see [here for master](https://github.com/oauth-xx/oauth2/blob/master/lib/oauth2/client.rb#L64) .  

Is there a way to get around it for v1.4.1?   e.g: pass in some kind of `connection_opts` when constructing the OAuth2::Client ?

**Comment by anvox** [comment]
@nahzz Could you puts your `faraday` versions and the code raise warning for more context? 
Especially, the code create `OAuth2::Client`. 

As I see in `v1.4.1`, oauth2 just leaves these config to caller. 

Thanks.

**Comment by pboling** [comment]
@nahzz 1.4.1 is not supported.  If you upgrade to the latest release version, version 1.4.4, then Faraday issues should be resolved.  There should not be any breaking changes.

1.4.5 should be released within a day or so.

**Comment by pboling** [comment]
I am going to close this.  Please create a new issue if this continues to be the case with the **current** version of the gem.
