### ISSUE TITLE
[QUESTION] How to cache OAuth2::AccessToken?

### ISSUE THREAD

**Issue by aesyondu** [oauth-xx/oauth2#505]
I'm doing something like this:

```ruby
token = Rails.cache.fetch(CACHE_KEY.to_s, expires_in: 1.hour) do
  client = OAuth2::Client.new(CLIENT_ID, CLIENT_SECRET,
                              site: SITE,
                              token_url: OAUTH_ENDPOINT)
  client.client_credentials.get_token
end
```

But it throws an error:

`TypeError (no _dump_data is defined for class OpenSSL::X509::Store):`

I'm only doing it because I want to reuse the access token and not request a new one for every request. Is there a better way to store the token?

----

Right now my workaround is `to_hash`:

```ruby
client = OAuth2::Client.new(CLIENT_ID, CLIENT_SECRET,
                            site: SITE,
                            token_url: OAUTH_ENDPOINT)

token_hash = Rails.cache.fetch(CACHE_KEY.to_s + 'abc', expires_in: 1.hour) do
  client.client_credentials.get_token.to_hash
end

token = OAuth2::AccessToken.new client, token_hash

if token.expired?
  token_hash = Rails.cache.fetch(CACHE_KEY.to_s, expires_in: 1.hour, force: true) do
    client.client_credentials.get_token
  end

  OAuth2::AccessToken.new client, token_hash
else
  token
end
```

**Comment by anvox** [comment]
I think it's reason why `OAuth2::AccessToken#to_hash` and `OAuth2::AccessToken.from_hash` exist. 

The cached content must be serializable, but for complex objects like `OAuth2::AccessToken`, I don't think we have any cache store could handle. Besides, mostly in production, Rails cache are shared between processes, you won't want to share an object much like that. 

In my projects, it looks like this 

```ruby
def cached_token
  client = OAuth2::Client.new(CLIENT_ID, CLIENT_SECRET,
                              site: SITE,
                              token_url: OAUTH_ENDPOINT)
  token_hash = Rails.cache.fetch(CACHE_KEY.to_s, expires_in: 1.hour) do
    client.client_credentials.get_token.to_hash
  end

  OAuth2::AccessToken.from_hash(client, token_hash)
end
```

And refresh/re-get_token if expired before getting resources.

**Comment by anvox** [comment]
Added to wiki https://github.com/oauth-xx/oauth2/wiki/Basic-usage#store-and-restore-token

**Comment by aesyondu** [comment]
Very nice, thank you!
