### ISSUE TITLE
Can't get access token from Microsoft Azure

### ISSUE THREAD

**Issue by Drblack101** [oauth-xx/oauth2#522]
I can get the authorization code from Azure w/o issue. Then when I use this auth code to request token, it returns me all errors even I've tried so many different calls.

Errors message is like: "NoMethodError - undefined method `auth_code' for #<OAuth2::AccessToken:0x0000565354ea2470>:"
"OAuth2::AccessToken:0x0000565356f2aa30", empty token....
``# method 1
 token = OAuth2::AccessToken.from_hash(client, properties)
# method 2
 token = client.auth_code.get_token(code, :redirect_uri => 'http://localhost:8080/user/oauth2/callback')
#method 3
result1 = client.auth_code.authorize_url(:redirect_uri => 'http://localhost:8080/user/oauth2/callback')
``

**Comment by anvox** [comment]
@Drblack101 3 methods you mentioned
`token = OAuth2::AccessToken.from_hash(client, properties)` is used to retrieve token from a saved hash. 
`result1 = client.auth_code.authorize_url(:redirect_uri => 'http://localhost:8080/user/oauth2/callback')` generate authorize url. 

The correct way to exchange auth_code for token is `token = client.auth_code.get_token(code, :redirect_uri => 'http://localhost:8080/user/oauth2/callback')`. Could you help to put detail result/error of this method?

**Comment by Drblack101** [comment]
Hi anvox, thanks for the quick response. Here's the code structure I've tried:

I got the auth code successfully from Azure, then I give that value to variable "code", then parse the code when I use the get_token method, but got OAuth2::Error point to the line of that "get_token":

OAuth2::Error - :
  oauth2 (1.4.2) lib/oauth2/client.rb:119:in `request'
  oauth2 (1.4.2) lib/oauth2/client.rb:146:in `get_token'
  oauth2 (1.4.2) lib/oauth2/strategy/auth_code.rb:30:in `get_token'

`client = OAuth2::Client.new(client_id, client_secret, :site => site_path, :authorize_url => auth_url, :token_urld => token_url, :scope => scope, :grant_type => 'authorization_code')`
`token = client.auth_code.get_token(code, :redirect_uri => 'http://localhost:8080/users/oauth2/callback')`

**Comment by anvox** [comment]
Could you try on latest version 1.4.4. 
I'm looking into detail, but I guess your current config for exchange token may not meet Azure.

**Comment by Drblack101** [comment]
I've updated to 1.4.4. But got the same result, same error message points to "get_token" method. I've used the OAuth2 configuration on Postman and can get Azure token without any problem.

**Comment by anvox** [comment]
It works without any change? Great to hear that 😂 But if you find anything in config to share, I'll happy to update the document for it. Thanks @Drblack101

**Comment by Drblack101** [comment]
Got a dumb question here, when I inspect the "token" variable, it returns the following format, how I can extract the value like token?
`#<OAuth2::AccessToken:0x0000563e31b977b8 `
`@client=#<OAuth2::Client:0x0000563e30554238 `
`@id="8a4fd204-7d2e-422f-b73b-d45c8d382223", `
`@site="https://login.microsoftonline.com", `
`@token="eyJ0eXAiOiJKV1QiLCJub25jZSI6InJKWnJkOUpvVVpUMlRnVXZQR3hi..."`
`@expires_at=1599681692, `
`@options={:mode=>:header, :header_format=>"Bearer %s", :param_name=>"access_token"}, `

Thanks!

**Comment by Drblack101** [comment]
OK, i'm gonna answer my own question: 
`token.token`  will return the token variable in this case.
