### ISSUE TITLE
'problem+json' error format

### ISSUE THREAD

**Issue by janz93** [oauth-xx/oauth2#545]
All our APIs are protected via oauth2 and we make use of this gem.

The [`OAuth2::Error class`](https://github.com/oauth-xx/oauth2/blob/ebe95171c3d34b9f8f4a4dfdca2e5094efc2deee/lib/oauth2/error.rb) is expecting the error response to always have an `error`, `error_description` parameter

Our APIs make use of the [`problem+json`](https://tools.ietf.org/html/rfc7807) as a structured format for error messages.

I was reading through the [oauth2 spec](https://tools.ietf.org/html/rfc6749#section-7.2) and if I understood the spec correctly it says that the resource error response format can look however you want it to be.

Maybe it would be great to support different error formats like `problem+json` 

PS. All thanks for the hard work that goes into this gem ❤️

**Comment by pboling** [comment]
Interesting idea.  I would have guessed, based solely on your description that "error response format" would be referring to the content and format of the **response body**, rather than the `CONTENT_TYPE`.  I would need to review the spec to understand what the requirements are for `CONTENT_TYPE`.
