### ISSUE TITLE
Error: no _dump_data is defined for class Proc

### ISSUE THREAD

**Issue by katherinlaine** [oauth-xx/oauth2#548]
Hello! We've just upgraded from `1.4.4` to `1.4.7` and are having a bit of an issue with the new proc format of the token when trying to deserialize a cached version. 

Given a valid OAuthClient:

      OAuth2::Client.new(
        "",
        "",
        authorize_url: AUTH_URL,
        token_url: TOKEN_URL,
      )

and an `access token` via Signet::OAuth2::Client, 

```
ActiveSupport::Cache::MemoryStore.new.fetch(:x) do
   OAuth2::AccessToken.new(oauth_client, access_token["access_token"])
end
```
we get the following error:

```
[2021-06-01T16:59:44] DEBUG ActiveSupport::Cache::NullStore : Cache read: x ({:compress=>false})
[2021-06-01T16:59:44] DEBUG ActiveSupport::Cache::NullStore : Cache generate: x ({:compress=>false})
[2021-06-01T16:59:44] DEBUG ActiveSupport::Cache::NullStore : Cache write: x ({:compress=>false})
TypeError: no _dump_data is defined for class Proc
```

Does anyone have advice on the best way to resolve, or is there any other information you'd need? Prior to the changes in `1.4.5` it worked and was deserialized just fine. 

Thanks!

**Comment by newbray** [comment]
there are some rails minor version updates available such as activerecord 6.1.3.1 to 6.1.3.2 - might be worth a bundle update on this branch

**Comment by pboling** [comment]
@katherinlaine Additionally, please try out `master` branch with your app.  See the changelog for the minor breaking changes, which may or may not affect you.

**Comment by pboling** [comment]
It is worth noting that the proc format of the token is deprecated, and will no longer be supported in future releases.  The best way to handle the token, is by creating a class, and passing the class.  The class must define `.from_hash` as a class method.

**Comment by pboling** [comment]
Since the proc format will die with the 1.4.x line of gems I'm closing this.
