### ISSUE TITLE
Add support for different client authentication methods

### ISSUE THREAD

**Issue by jamietanna** [oauth-xx/oauth2#556]
More providers are moving over to different authentication methods like `private_key_jwt` so it'd be great to be able to support this, and other authentication methods that are in use, with this library.

**Comment by pboling** [comment]
@jamietanna private jwt key is JWT with the `RS256` algorithm, and we do support that method!  See https://github.com/oauth-xx/oauth2/blob/master/spec/oauth2/strategy/assertion_spec.rb#L112
