### ISSUE TITLE
support faraday 2.x?

### ISSUE THREAD

**Issue by jrochkind** [oauth-xx/oauth2#559]
Faraday 2.x has been released. 

The gemspec here (even on master branch), requires `< 2` for faraday. 

Could oauth2 support faraday 2.x, for compatibility with apps that have other dependencies that require faraday 2.x or otherwise want to use it? 

Could that even be backported to an oauth2 1.x release?

**Comment by renchap** [comment]
As an alternative to upgrading to Faraday 2, would you consider dropping the dependency on Faraday?

It often results in conflicts with other gems or apps that use Faraday and major version bumps might be hard to manage.

**Comment by ivobenedito** [comment]
#565 #562

**Comment by prasanna** [comment]
> As an alternative to upgrading to Faraday 2, would you consider dropping the dependency on Faraday?
> 
> It often results in conflicts with other gems or apps that use Faraday and major version bumps might be hard to manage.

Good thought. Will have to test OAuth without the nice API that Faraday provides.

**Comment by jrochkind** [comment]
I believe this is resolved by #561, just needs a release.
