### ISSUE TITLE
Ruby 3.0 support

### ISSUE THREAD

**Issue by clarkedb** [oauth-xx/oauth2#564]
From #536 it looks like ruby 3.0 will be supported in the next release. Is it already supported in the most recent release 1.4.7? If not, is there a timeline for the next release?

**Comment by pboling** [comment]
Ruby 3 is part of the build matrix, and should be supported in the current release.  Please let me know if you find otherwise.

**Comment by clarkedb** [comment]
> Ruby 3 is part of the build matrix, and should be supported in the current release. Please let me know if you find otherwise.

I will submit an issue if I run into a problem. Thank you.
