### ISSUE TITLE
Earlier release of 2.0?

### ISSUE THREAD

**Issue by stanhu** [oauth-xx/oauth2#585]
@pboling Thanks for all your work here! I'd love to get a release 2.0, particularly to pull in https://github.com/oauth-xx/oauth2/pull/509 since this gets rid of MD5, which is necessary for FIPS compliance.

I see https://github.com/oauth-xx/oauth2/milestone/1 is the goal, but could we push these to a 2.1 release?

**Comment by stanhu** [comment]
Are https://github.com/oauth-xx/oauth2/issues/582 and https://github.com/oauth-xx/oauth2/issues/248 the main issues that need help?

**Comment by stanhu** [comment]
Ok, I think the 2.0 issues are complete now. I think the mutual TLS issue can probably be left alone now: https://github.com/oauth-xx/oauth2/issues/583#issuecomment-1151595579. As far as I can tell, no code changes are necessary on the client.

Could we cut a release soon? Thanks again!

**Comment by pboling** [comment]
Everything looks great!  I'll start the release process 🎸

**Comment by pboling** [comment]
@stanhu I have released `2.0.0.rc1`.  Please try it out!

**Comment by stanhu** [comment]
@pboling Thank you!

I did a diff between `v1.4.9` and `v2.0.0.rc1`:

- In `v1.4.9`, if there were a JSON or XML parser error in `#get_token`, the client would catch the exception and return `nil`. I'm wondering if this is could lead to errors bubbling up unexpectedly.
- Wondering if `OAuth2::Client#refresh!` should use a keyword argument `access_token_class` to be consistent with `OAuth2::Client#get_token`.

**Comment by stanhu** [comment]
Ok, I see `raise_errors` was default to `true`, so the exception would be thrown in `v1.4.9` as well.

**Comment by pboling** [comment]
@stanhu On the first point, raising was an intentional breaking change. https://github.com/oauth-xx/oauth2/pull/576

**Comment by pboling** [comment]
On the second point, yeah, I think it makes sense to have the arguments share a common pattern.

**Comment by stanhu** [comment]
#595 should resolve a regression, and #596 should make the arguments consistent.

**Comment by pboling** [comment]
I will have a look at them when I get back to my computer!

**Comment by pboling** [comment]
@stanhu 2.0.0.rc2 has been released with those changes

**Comment by stanhu** [comment]
@pboling Thank you! One more bug fix with error handling: https://github.com/oauth-xx/oauth2/pull/598

**Comment by pboling** [comment]
@stanhu 2.0.0.rc3 is released!

**Comment by pboling** [comment]
@stanhu 2.0.0 is released!

**Comment by stanhu** [comment]
@pboling Thank you so much! I was just going to say that I've been testing our OAuth2 integrations with the pre-release version, and everything looks good.
