### ISSUE TITLE
Missing v2.0.0 Release Artifacts?

### ISSUE THREAD

**Issue by nbibler** [oauth-xx/oauth2#602]
It _looks_ like there was a [v2.0.0 release on Rubygems](https://rubygems.org/gems/oauth2/versions/2.0.0) earlier today. However, I'm not seeing a git tag in this repo, nor an updated CHANGELOG, nor an updated README (it still refers to 2.x as an "(unreleased, master branch)" for instance).

I'm less pinging here as a reminder to do those things and more as a "this feels weird that the team pushed a new major release and forgot a bunch of stuff, was this push/release accidental?"

**Comment by pboling** [comment]
I got interrupted as I was checking things off the list.  Tag has been pushed!  Working on the others.

**Comment by pboling** [comment]
Done!

**Comment by pboling** [comment]
This is the first major release that I've done on this project, and over the 4 years I've worked preparing this release the mentions of 2.0.0 being unreleased multiplied, and I failed to snipe them all before the release.
