### ISSUE TITLE
Version 2.0.5 seems to include a breaking change

### ISSUE THREAD

**Issue by mvz** [oauth-xx/oauth2#623]
The changelog for 2.0.5 reads "BREAKING: Microsoft's id_token is no longer left as access_token['id_token'], but moved to the standard access_token.token that all other strategies use". Since this is a breaking change it seems the major version number should have been bumped. I'm reporting this bug as per the versioning section in the README.

**Comment by pboling** [comment]
Thanks for the report @mvz.  Yeah, it was a breaking change, but fixing an old bug.  I'll look into that code raising an error.  We now have 100% test coverage, so it should be simple to figure out!

**Comment by mvz** [comment]
The error seems to be raised by the new code starting here: https://github.com/oauth-xx/oauth2/pull/621/files#diff-b665e6fc2096be34f9c5e92cb0f38eb3a229da37ed4da92487f0a834eb6ae336R53.

**Comment by pboling** [comment]
Aha!  I misunderstood the error initially.

```
      if @client.options[:raise_errors] && (@token.nil? || @token.empty?) && (@refresh_token.nil? || @refresh_token.empty?)
```
If I test for a token or refresh_token, it should fix the immediate issue of the error being raised.
@mvz Would that be sufficient for you?

**Comment by mvz** [comment]
> Would that be sufficient for you?

Yes, that would fix the error for me. I could still be a breaking change for other people, but maybe things crash and burn anyway if you leave out both tokens :slightly_smiling_face:.

Thanks for taking care of this!

**Comment by pboling** [comment]
@mvz v2.0.6 has been released!   Please let me know if that fixes it for you.
