### ISSUE TITLE
Doesn't reuse the refresh token

### ISSUE THREAD

**Issue by dgutov** [oauth-xx/oauth2#67]
I'm using this gem to authenticate with Google APIs. When I do

```
token = token.refresh!
```

the new access token always has `refresh_token` field empty.
If I assign it the previous `refresh_token` manually, it works on the next refresh.

[The draft](http://tools.ietf.org/html/draft-ietf-oauth-v2-18#section-1.5) section 1.5 step H says that issuing a new refresh token is optional, so maybe you should handle the case when the response to refresh request doesn't contain a refresh token and reuse the previous one.

**Comment by josephpage** [comment]
It's now implemented.
If the response does not contain a refresh_token, the access_token hash will contains the same refresh_token.
https://github.com/oauth-xx/oauth2/blob/075e0c5a836c5b041702571e47e3b50d8dcc8600/lib/oauth2/access_token.rb#L88
