### ISSUE TITLE
2-legged OAuth

### ISSUE THREAD

**Issue by marisademeglio** [oauth-xx/oauth2#74]
This is more of a feature request: I'd like to use this library for 2-legged OAuth.  As far as I can tell, it's not supported, because there's no way to get a connection without having to go through a token.  My understanding is that 2-legged OAuth does not use tokens -- it uses only a client ID and secret, formatted correctly (regarding the HTTP headers), and transmitted via HTTPS.

If it's already possible, please let me know and delete this issue.

**Comment by josephpage** [comment]
Client credentials is actually implemented in the gem. See the README.

**Comment by pboling** [comment]
And as for https://github.com/pelle/oauth-plugin, it uses this gem for the Oauth2 parts, :)
