### ISSUE TITLE
Client get_token method raises error incorrectly

### ISSUE THREAD

**Issue by amnwebmaster** [oauth-xx/oauth2#75]
Calling @client.auth_code.get_token(...) to Facebook gives an OAuth2::Error

Facebook correctly returns the access token but not as a hash but a string hence client.rb line 130 is incorrect

raise Error.new(response) unless response.parsed.is_a?(Hash) && response.parsed['access_token']

Should be:
raise Error.new(response) unless response.parsed['access_token']

**Comment by anvox** [comment]
I summarized this thread to this wiki [Custom response parsing](https://github.com/oauth-xx/oauth2/wiki/Advanced-usage#custom-response-parsing). Please help to comment if any missing. 
Close as solution documented.
